### ISSUE TITLE
Possible Unhandled Promise Rejection: ReferenceError: Property 'y' doesn't exist on Spark AR V137 & V138

### ISSUE THREAD

**Issue by Singforthelaughter** [pofulu/sparkar-pftween#10]
WARNING: Possible Unhandled Promise Rejection: ReferenceError: Property 'y' doesn't exist
   {
     "line": 743,
     "column": 44,
     "sourceURL": "PFTween.ts"
   }
   
   Warning occurs when I try to animate a plane using PFTween. Below are the code I used. 

`(async function () {

  const plane = await S.root.findFirst('plane0');

  plane.transform.y = new PFTween(0.5, -0.5, 3000).setLoops().scalar;

})(); 
![Code_xRuPovjkxL](https://user-images.githubusercontent.com/52593240/169683715-e7b46a2b-4198-4f5d-9538-8298bbe1ceec.png)
![ARStudioWindows_vS6Xeld6c0](https://user-images.githubusercontent.com/52593240/169683716-1a44e210-8d16-4df7-9fde-3dda12f04dc9.png)
`

**Comment by pofulu** [comment]
I guess it caused by some transpile configures changed in SparkAR.
The new release v1.2.3 works in my test. You can just download it from README.

Thanks for the report!
